name: Build packages

on:
  push:
    paths:
      - "fedora/specs/**"
      - "fedora/graph.yml"
  workflow_dispatch:
jobs:
  rpm:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    container:
      image: fedora:44

    steps:
      - uses: actions/checkout@v4

      - name: Install RPM tools
        run: |
          dnf install -y \
            rpm-build \
            rpmdevtools \
            dnf-plugins-core \
            spectool \
            yq \
            createrepo_c

      - name: Setup rpmbuild tree
        run: |
          rpmdev-setuptree

      - name: Build dependencies
        run: |
          set -e
          graph=fedora/graph.yml

          deps=$(yq -r '.dependencies[]' "$graph")

          mkdir ~/dependencies

          for package in $deps; do
            cp "fedora/specs/$package.spec" ~/rpmbuild/SPECS/
            spec=~/rpmbuild/SPECS/$package.spec
            package_name=$(rpmspec -q --qf "%{NVRA}\n" "$spec")

            spectool -g -R $spec
            dnf builddep -y $spec
            rpmbuild -ba $spec

            mv "$HOME/rpmbuild/RPMS/x86_64/"* ~/dependencies/
          done

          createrepo_c ~/dependencies/
          echo "[dependencies]
          name=dependencies
          baseurl=file://$HOME/dependencies
          enabled=1
          gpgcheck=0" | sudo tee /etc/yum.repos.d/dependencies.repo

          dnf makecache
      - name: Build packages
        run: |
          set -e
          graph=fedora/graph.yml

          packages=$(yq -r '.packages[]' "$graph")

          for package in $packages; do
            cp "fedora/specs/$package.spec" ~/rpmbuild/SPECS/
            spec=~/rpmbuild/SPECS/$package.spec
            spectool -g -R $spec
            dnf builddep -y $spec
            rpmbuild -ba $spec
          done

      - name: Upload RPMs
        uses: actions/upload-artifact@v4
        with:
          name: rpm-packages
          path: |
            ~/rpmbuild/RPMS/**/*.rpm

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "packages-fedora"
          artifacts: "~/rpmbuild/RPMS/**/*.rpm"
          token: ${{ secrets.GITHUB_TOKEN }}
